DROP DATABASE IF EXISTS employees_db;
CREATE DATABASE employeeses_db;

USE employees_db;

CREATE TABLE department (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  department VARCHAR(100) NOT NULL
);

CREATE TABLE role (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    salary INT NOT NULL,
    FOREIGN KEY (department)
    REFERENCES department(id)
    ON DELETE SET NULL
);

CREATE TABLE employee (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    salary INT NOT NULL,
    FOREIGN KEY (role)
    REFERENCES role(id)
    ON DELETE SET NULL
);

/** ^^ NOT SURE IF FOREIGN KEY SETUP CORRECTLY?? 